sources:
- 169.254.119.103
- 169.254.119.106
- 169.254.119.107
- 169.254.119.108
weights_path: components/biz/weights/30010001-1.pt
hz_classes:
- t3
- t3-1
- t7-1
- t7-2
hz_conf:
- 0.8
- 0.8
- 0.85
- 0.8
- 0.5
- 0.5
- 0.5
- 0.5
- 0.5
hz_classes_ok_num:
- 1
- 0
- 1
- 0
- 0
four_cameras:
  hz_classes:
  - t1
  - t1-1
  ca_id: []
  ymax:
  - 0
  - 1
  ymin:
  - 3
  - 4
center_camera:
  hz_classes:
  - t3
  - t3-1
  - t7-1
  - t7-2
  ca_id:
  - 0
  roi_ymax: 750
  roi_ymin: 200
hz_check_name_ok:
- t3
- t7
hz_check_name_ng:
- t3-1
- t7-1
hz_check_flage_conf: 85
ng_fps: 2
ok_fps: 1
filter_hj_model: temp_check_pass
show_box_test: true
isbox_findContours: false
isbox_dt: true
threshold: 60
min_c_y: 360
max_c_y: 460
max_box_area: 600000
min_box_area: 70000
hz_xy_check: false
dingtiao:
  dingtiao_weights_path: components/biz/weights/dingtiao.pt
  dingtiao_detect: true
  dt-class:
  - t1-2
  dt_x_roi:
  - - 700
    - 900
  - - 700
    - 900
  - - 700
    - 900
  dt_y_roi:
  - - 240
    - 890
  - - 470
    - 900
  - - 50
    - 540
  dt_num_ca:
  - 1
  - 2
  - 3
  dt_ca_names:
  - 1
  - 3
  dt_num_ok:
  - 1
  - 1
  - 1
wz:
  wz_class_name: []
  wz_class: []
  x_check_ok: []
  y_check_ok: []
new_model: true
